### ISSUE TITLE
Revamp folder structure for better maintainability

### ISSUE THREAD

**Issue by rekpero** [ChristianOConnor/spheron-react-api-stack#2]
Let's revamp the current folder structure since we will be building 2 separate projects in a single repo. Let's go for a monorepo structure -
```
server
-- src
---- index.js
-- Dockerfile
-- package.json

react/frontend
-- src
---- App.jsx
---- index.js
-- package.json
```

**Comment by ChristianOConnor** [comment]
I changed up the project structure to what you described in this commit 3cc4dcddc8efa474212c329f507546de0e1627fc. As of 3cc4dcddc8efa474212c329f507546de0e1627fc it doesn't run because I haven't built the express server yet.
