### ISSUE TITLE
Create an express app (javascript)

### ISSUE THREAD

**Issue by rekpero** [ChristianOConnor/spheron-react-api-stack#3]
We must create an express app to put our logic in the netlify function. We will need a single endpoint rest API.

**Comment by ChristianOConnor** [comment]
I did this. See in the readme as of commit 134dd85c894b8845660723dc2b31e477aade933a. the server works and listens at "http://localhost:8081/hello"

**Comment by rekpero** [comment]
@ChristianOConnor, that's great. We can move to our third step, where we need to add the Dockerfile. Please follow the #4 issue for this step.
