### ISSUE TITLE
Create dockerfile for gererating an docker image

### ISSUE THREAD

**Issue by rekpero** [ChristianOConnor/spheron-react-api-stack#4]
We need to create a Dockerfile config to generate an image from the server.
Ref blog - https://blog.spheron.network/docker-part-1/

**Comment by ChristianOConnor** [comment]
I did this. It works with the backend API being completely run in a docker container.

**Comment by ChristianOConnor** [comment]
I did this. It works with the backend API being completely run in a docker container.

I completed everything listed in your issues. It's now a React app that connects with an express backend run entirely in a docker container. I need you @rekpero or @izrake to take over the code from here. I don't know how to deploy this on Spheron or create an authentication between the frontend and the backend. Please take over from here.

P.S. You can change the backend if you want. I have it calling a Google Cloud Function, but to simplify the app you can just have it spit out a string or something like that
